function GetSongColor(songtit)
	--Yellow-#FFFF00
	--Lime-#00FF00
	--Cyan-#00FFFF

	--Arcade Colors
	local ACSong = {
		--Yellow
		[".59"] = "#FFFF00",
		["DAM DARIRAM (KCP MIX)"] = "#FFFF00",
		["Don't Stop!~AMD 2nd MIX~"] = "#FFFF00",
		["era (nostalmix)"] = "#FFFF00",
		["Get me in your sight (AMD CANCUN MIX)"] = "#FFFF00",
		["HERO (HAPPY GRANDALE MIX)"] = "#FFFF00",
		["Holic"] = "#FFFF00",
		["IF YOU WERE HERE (B4 ZA BEAT MIX)"] = "#FFFF00",
		["LEADING CYBER"] = "#FFFF00",
		["Let's talk it over"] = "#FFFF00",
		["Make Your Move"] = "#FFFF00",
		["never let you down"] = "#FFFF00",
		--Lime
		["1,2,3,4, 007"] = "#00FF00",
		["AFTER THE GAME OF LOVE"] = "#00FF00",
		["B4U"] = "#00FF00",
		["BA KKWO"] = "#00FF00",
		["BABY BABY GIMME YOUR LOVE"] = "#00FF00",
		["BOYS (EURO MIX)"] = "#00FF00",
		["BU DAM"] = "#00FF00",
		["BUMBLE BEE"] = "#00FF00",
		["BURNIN' THE FLOOR"] = "#00FF00",
		["BYUL"] = "#00FF00",
		["CAN'T STOP FALLIN' IN LOVE"] = "#00FF00",
		["CUTIE CHASER"] = "#00FF00",
		["DREAM A DREAM"] = "#00FF00",
		["DROP OUT"] = "#00FF00",
		["DROP THE BOMB"] = "#00FF00",
		["EAT YOU UP"] = "#00FF00",
		["FACE"] = "#00FF00",
		["FURUHATA'S THEME"] = "#00FF00",
		["GIMME GIMME GIMME"] = "#00FF00",
		["GOTCHA (The Theme From STARSKY & HUTCH)"] = "#00FF00",
		["HAVE YOU NEVER BEEN MELLOW (MM GROOVIN MIX)"] = "#00FF00",
		["HERO (KCP DISCOTIQUE MIX)"] = "#00FF00",
		["HIGHER"] = "#00FF00",
		["HYPNOTIC CRISIS"] = "#00FF00",
		["HYSTERIA"] = "#00FF00",
		["IN THE HEAT OF THE NIGHT"] = "#00FF00",
		["KICK THE CAN"] = "#00FF00",
		["La Senorita Virtual"] = "#00FF00",
		["Let the beat hit em!"] = "#00FF00",
		["LOVE AGAIN TONIGHT~For Melissa MIX~"] = "#00FF00",
		["LOVE THIS FEELIN'"] = "#00FF00",
		["MUSIC"] = "#00FF00",
		["MY SUMMER LOVE"] = "#00FF00",
		["NEVER GONNA MAKE (FACTORY DANCE TEAM MIX)"] = "#00FF00",
		["NIGHT IN MOTION"] = "#00FF00",
		["ONE TWO (LITTLE BITCH)"] = "#00FF00",
		["ONLY YOU"] = "#00FF00",
		["ORION.78(AMeuro-MIX)"] = "#00FF00",
		["PARANOIA EVOLUTION"] = "#00FF00",
		["PINK DINOSAUR"] = "#00FF00",
		["SAINT GOES MARCHING (REMIX)"] = "#00FF00",
		["SHAKE YOUR BOOTY"] = "#00FF00",
		["SHOOTING STAR"] = "#00FF00",
		["SUNG SUK"] = "#00FF00",
		["SUPER STAR"] = "#00FF00",
		["TELL ME TELL ME"] = "#00FF00",
		["THE 7 JUMP"] = "#00FF00",
		["think ya better D"] = "#00FF00",
		["TRIP MACHINE CLIMAX"] = "#00FF00",
		["TRIP MACHINE~luv mix~"] = "#00FF00",
		["WA"] = "#00FF00",
		["WALKIE TALKIE"] = "#00FF00",
		["WILD RUSH"] = "#00FF00",
		["Young Forever"] = "#00FF00",
		--Cyan
		["20,NOVEMBER (D.D.R. version)"] = "#00FFFF",
		["AFRONOVA"] = "#00FFFF",
		["AM-3P"] = "#00FFFF",
		["BAD GIRLS"] = "#00FFFF",
		["Boom Boom Dollar (Red Monster Mix)"] = "#00FFFF",
		["BOOM BOOM DOLLAR (K.O.G G3 MIX)"] = "#00FFFF",
		["Boys"] = "#00FFFF",
		["BRILLIANT 2U"] = "#00FFFF",
		["BRILLIANT 2U(Orchestra Groove)"] = "#00FFFF",
		["Butterfly"] = "#00FFFF",
		["butterfly (UPSWING MIX)"] = "#00FFFF",
		["CAPTAIN JACK (GRANDALE REMIX)"] = "#00FFFF",
		["DAM DARIRAM"] = "#00FFFF",
		["DEAD END"] = "#00FFFF",
		["DO IT ALL NIGHT"] = "#00FFFF",
		["DUB-I-DUB"] = "#00FFFF",
		["DYNAMITE RAVE"] = "#00FFFF",
		["EL RITMO TROPICAL"] = "#00FFFF",
		["END OF THE CENTURY"] = "#00FFFF",
		["FLASHDANCE (WHAT A FEELING)"] = "#00FFFF",
		["FOLLOW THE SUN (90 IN THE SHADE MIX)"] = "#00FFFF",
		["gentle stress (AMD SEXUAL MIX)"] = "#00FFFF",
		["GET UP (BEFORE THE NIGHT IS OVER)"] = "#00FFFF",
		["GET UP AND DANCE"] = "#00FFFF",
		["GET UP'N MOVE"] = "#00FFFF",
		["GRADIUSIC CYBER ~AMD G5 MIX~"] = "#00FFFF",
		["HAVE YOU NEVER BEEN MELLOW"] = "#00FFFF",
		["HERO"] = "#00FFFF",
		["HOLIDAY"] = "#00FFFF",
		["I Believe In Miracles (The Lisa Marie Experience Radio Edit)"] = "#00FFFF",
		["IF YOU CAN SAY GOODBYE"] = "#00FFFF",
		["IF YOU WERE HERE"] = "#00FFFF",
		["IN THE NAVY '99 (XXL Disaster Remix)"] = "#00FFFF",
		["IT ONLY TAKES A MINUTE (Extended Remix)"] = "#00FFFF",
		["Jam Jam Reggae"] = "#00FFFF",
		["KEEP ON MOVIN'"] = "#00FFFF",
		["KUNG FU FIGHTING"] = "#00FFFF",
		["La Senorita"] = "#00FFFF",
		["LET THEM MOVE"] = "#00FFFF",
		["LET'S GET DOWN"] = "#00FFFF",
		["Little Bitch"] = "#00FFFF",
		["LOVE"] = "#00FFFF",
		["LUV TO ME (AMD MIX)"] = "#00FFFF",
		["MAKE A JAM!"] = "#00FFFF",
		["MAKE IT BETTER"] = "#00FFFF",
		["MAKE IT BETTER (So-REAL Mix)"] = "#00FFFF",
		["MR. WONDERFUL"] = "#00FFFF",
		["My Fire (UKS Remix)"] = "#00FFFF",
		["OH NICK PLEASE NOT SO QUICK"] = "#00FFFF",
		["OPERATOR"] = "#00FFFF",
		["PARANOiA"] = "#00FFFF",
		["PARANOiA KCET ~clean mix~"] = "#00FFFF",
		["PARANOiA MAX~DIRTY MIX~"] = "#00FFFF",
		["PARANOiA Rebirth"] = "#00FFFF",
		["PUT YOUR FAITH IN ME"] = "#00FFFF",
		["PUT YOUR FAITH IN ME (Jazzy Groove)"] = "#00FFFF",
		["ROCK BEAT"] = "#00FFFF",
		["Silent Hill"] = "#00FFFF",
		["Smoke"] = "#00FFFF",
		["SP-TRIP MACHINE~JUNGLE MIX~"] = "#00FFFF",
		["stomp to my beat"] = "#00FFFF",
		["That's The Way (I Like It)"] = "#00FFFF",
		["THE RACE"] = "#00FFFF",
		["TRIP MACHINE"] = "#00FFFF",
		["TUBTHUMPING"] = "#00FFFF",
		["TURN ME ON (HEAVENLY MIX)"] = "#00FFFF",
		["UPSIDE DOWN"] = "#00FFFF",
		["VOL.4"] = "#00FFFF",
		["WONDERLAND (UKS MIX)"] = "#00FFFF",
		["XANADU"] = "#00FFFF",
	}

	--Arcade Asia Ver.
	local ACAsSong = {
		--Lime
		["1,2,3,4, 007"] = "#00FF00",
		["AFTER THE GAME OF LOVE"] = "#00FF00",
		["B4U"] = "#00FF00",
		["BABY BABY GIMME YOUR LOVE"] = "#00FF00",
		["BOYS (EURO MIX)"] = "#00FF00",
		["BU DAM"] = "#00FF00",
		["BUMBLE BEE"] = "#00FF00",
		["BURNIN' THE FLOOR"] = "#00FF00",
		["CAN'T STOP FALLIN' IN LOVE"] = "#00FF00",
		["CUTIE CHASER"] = "#00FF00",
		["DREAM A DREAM"] = "#00FF00",
		["DROP OUT"] = "#00FF00",
		["DROP THE BOMB"] = "#00FF00",
		["EAT YOU UP"] = "#00FF00",
		["FURUHATA'S THEME"] = "#00FF00",
		["GIMME GIMME GIMME"] = "#00FF00",
		["GOTCHA (The Theme From STARSKY & HUTCH)"] = "#00FF00",
		["HAVE YOU NEVER BEEN MELLOW (MM GROOVIN MIX)"] = "#00FF00",
		["HERO (KCP DISCOTIQUE MIX)"] = "#00FF00",
		["HIGHER"] = "#00FF00",
		["HYPNOTIC CRISIS"] = "#00FF00",
		["HYSTERIA"] = "#00FF00",
		["IF YOU CAN SAY GOODBYE"] = "#00FF00",
		["IN THE HEAT OF THE NIGHT"] = "#00FF00",
		["KICK THE CAN"] = "#00FF00",
		["La Senorita Virtual"] = "#00FF00",
		["Let the beat hit em!"] = "#00FF00",
		["LOVE AGAIN TONIGHT~For Melissa MIX~"] = "#00FF00",
		["LOVE THIS FEELIN'"] = "#00FF00",
		["MUSIC"] = "#00FF00",
		["MY SUMMER LOVE"] = "#00FF00",
		["NEVER GONNA MAKE (FACTORY DANCE TEAM MIX)"] = "#00FF00",
		["NIGHT IN MOTION"] = "#00FF00",
		["ONE TWO (LITTLE BITCH)"] = "#00FF00",
		["ONLY YOU"] = "#00FF00",
		["ORION.78(AMeuro-MIX)"] = "#00FF00",
		["PARANOIA EVOLUTION"] = "#00FF00",
		["PINK DINOSAUR"] = "#00FF00",
		["SAINT GOES MARCHING (REMIX)"] = "#00FF00",
		["SHAKE YOUR BOOTY"] = "#00FF00",
		["SHOOTING STAR"] = "#00FF00",
		["stomp to my beat"] = "#00FF00",
		["SUPER STAR"] = "#00FF00",
		["THE 7 JUMP"] = "#00FF00",
		["think ya better D"] = "#00FF00",
		["TRIP MACHINE CLIMAX"] = "#00FF00",
		["TRIP MACHINE~luv mix~"] = "#00FF00",
		["TUBTHUMPING"] = "#00FF00",
		["WALKIE TALKIE"] = "#00FF00",
		["WILD RUSH"] = "#00FF00",
		["XANADU"] = "#00FF00",
		["Young Forever"] = "#00FF00",
		--Cyan
		["20,NOVEMBER (D.D.R. version)"] = "#00FFFF",
		["AFRONOVA"] = "#00FFFF",
		["AM-3P"] = "#00FFFF",
		["BAD GIRLS"] = "#00FFFF",
		["Boom Boom Dollar (Red Monster Mix)"] = "#00FFFF",
		["BOOM BOOM DOLLAR (K.O.G G3 MIX)"] = "#00FFFF",
		["Boys"] = "#00FFFF",
		["BRILLIANT 2U"] = "#00FFFF",
		["BRILLIANT 2U(Orchestra Groove)"] = "#00FFFF",
		["Butterfly"] = "#00FFFF",
		["butterfly (UPSWING MIX)"] = "#00FFFF",
		["CAPTAIN JACK (GRANDALE REMIX)"] = "#00FFFF",
		["DAM DARIRAM"] = "#00FFFF",
		["DEAD END"] = "#00FFFF",
		["DO IT ALL NIGHT"] = "#00FFFF",
		["DUB-I-DUB"] = "#00FFFF",
		["DYNAMITE RAVE"] = "#00FFFF",
		["EL RITMO TROPICAL"] = "#00FFFF",
		["END OF THE CENTURY"] = "#00FFFF",
		["FLASHDANCE (WHAT A FEELING)"] = "#00FFFF",
		["FOLLOW THE SUN (90 IN THE SHADE MIX)"] = "#00FFFF",
		["gentle stress (AMD SEXUAL MIX)"] = "#00FFFF",
		["GET UP'N MOVE"] = "#00FFFF",
		["GRADIUSIC CYBER ~AMD G5 MIX~"] = "#00FFFF",
		["HAVE YOU NEVER BEEN MELLOW"] = "#00FFFF",
		["HERO"] = "#00FFFF",
		["HOLIDAY"] = "#00FFFF",
		["I Believe In Miracles (The Lisa Marie Experience Radio Edit)"] = "#00FFFF",
		["IF YOU WERE HERE"] = "#00FFFF",
		["IN THE NAVY '99 (XXL Disaster Remix)"] = "#00FFFF",
		["IT ONLY TAKES A MINUTE (Extended Remix)"] = "#00FFFF",
		["Jam Jam Reggae"] = "#00FFFF",
		["KEEP ON MOVIN'"] = "#00FFFF",
		["KUNG FU FIGHTING"] = "#00FFFF",
		["La Senorita"] = "#00FFFF",
		["LET THEM MOVE"] = "#00FFFF",
		["LET'S GET DOWN"] = "#00FFFF",
		["Little Bitch"] = "#00FFFF",
		["LUV TO ME (AMD MIX)"] = "#00FFFF",
		["MAKE A JAM!"] = "#00FFFF",
		["MAKE IT BETTER"] = "#00FFFF",
		["MAKE IT BETTER (So-REAL Mix)"] = "#00FFFF",
		["MR. WONDERFUL"] = "#00FFFF",
		["My Fire (UKS Remix)"] = "#00FFFF",
		["OH NICK PLEASE NOT SO QUICK"] = "#00FFFF",
		["OPERATOR"] = "#00FFFF",
		["PARANOiA"] = "#00FFFF",
		["PARANOiA KCET ~clean mix~"] = "#00FFFF",
		["PARANOiA MAX~DIRTY MIX~"] = "#00FFFF",
		["PARANOiA Rebirth"] = "#00FFFF",
		["PUT YOUR FAITH IN ME"] = "#00FFFF",
		["PUT YOUR FAITH IN ME (Jazzy Groove)"] = "#00FFFF",
		["ROCK BEAT"] = "#00FFFF",
		["Silent Hill"] = "#00FFFF",
		["Smoke"] = "#00FFFF",
		["SP-TRIP MACHINE~JUNGLE MIX~"] = "#00FFFF",
		["That's The Way (I Like It)"] = "#00FFFF",
		["THE RACE"] = "#00FFFF",
		["TRIP MACHINE"] = "#00FFFF",
		["TURN ME ON (HEAVENLY MIX)"] = "#00FFFF",
		["UPSIDE DOWN"] = "#00FFFF",
		["VOL.4"] = "#00FFFF",
		["WONDERLAND (UKS MIX)"] = "#00FFFF",
	}

	--Console Japan Colors
	local CSJPSong = {
		--Yellow
		["DANCING ALL ALONE"] = "#FFFF00",
		["Groove"] = "#FFFF00",
		["Midnite Blaze"] = "#FFFF00",
		["ORION.78~civilization mix~"] = "#FFFF00",
		["Share My Love"] = "#FFFF00",
		["SYNCHRONIZED LOVE (Red Monster Hyper Mix)"] = "#FFFF00",
		--Lime
		[".59"] = "#00FF00",
		["DAM DARIRAM (KCP MIX)"] = "#00FF00",
		["Don't Stop!~AMD 2nd MIX~"] = "#00FF00",
		["era (nostalmix)"] = "#00FF00",
		["Get me in your sight (AMD CANCUN MIX)"] = "#00FF00",
		["HERO (HAPPY GRANDALE MIX)"] = "#00FF00",
		["Holic"] = "#00FF00",
		["IF YOU WERE HERE (B4 ZA BEAT MIX)"] = "#00FF00",
		["LEADING CYBER"] = "#00FF00",
		["Let's talk it over"] = "#00FF00",
		["Make Your Move"] = "#00FF00",
		["never let you down"] = "#00FF00",
		--Cyan
		["1,2,3,4, 007"] = "#00FFFF",
		["B4U"] = "#00FFFF",
		["BABY BABY GIMME YOUR LOVE"] = "#00FFFF",
		["BOYS (EURO MIX)"] = "#00FFFF",
		["BUMBLE BEE"] = "#00FFFF",
		["BURNIN' THE FLOOR"] = "#00FFFF",
		["DREAM A DREAM"] = "#00FFFF",
		["EAT YOU UP"] = "#00FFFF",
		["FOLLOW THE SUN (90 IN THE SHADE MIX)"] = "#00FFFF",
		["FURUHATA'S THEME"] = "#00FFFF",
		["GIMME GIMME GIMME"] = "#00FFFF",
		["GOTCHA (The Theme From STARSKY & HUTCH)"] = "#00FFFF",
		["HAVE YOU NEVER BEEN MELLOW (MM GROOVIN MIX)"] = "#00FFFF",
		["HERO (KCP DISCOTIQUE MIX)"] = "#00FFFF",
		["HIGHER"] = "#00FFFF",
		["HYPNOTIC CRISIS"] = "#00FFFF",
		["IN THE HEAT OF THE NIGHT"] = "#00FFFF",
		["IT ONLY TAKES A MINUTE (Extended Remix)"] = "#00FFFF",
		["KICK THE CAN"] = "#00FFFF",
		["LOVE AGAIN TONIGHT~For Melissa MIX~"] = "#00FFFF",
		["MUSIC"] = "#00FFFF",
		["MY SUMMER LOVE"] = "#00FFFF",
		["NEVER GONNA MAKE (FACTORY DANCE TEAM MIX)"] = "#00FFFF",
		["NIGHT IN MOTION"] = "#00FFFF",
		["ONE TWO (LITTLE BITCH)"] = "#00FFFF",
		["ONLY YOU"] = "#00FFFF",
		["ORION.78(AMeuro-MIX)"] = "#00FFFF",
		["PINK DINOSAUR"] = "#00FFFF",
		["SAINT GOES MARCHING (REMIX)"] = "#00FFFF",
		["SHAKE YOUR BOOTY"] = "#00FFFF",
		["SHOOTING STAR"] = "#00FFFF",
		["THE 7 JUMP"] = "#00FFFF",
		["TRIP MACHINE CLIMAX"] = "#00FFFF",
		["WALKIE TALKIE"] = "#00FFFF",
		["XANADU"] = "#00FFFF",
		["Young Forever"] = "#00FFFF",
	}

	--Fallback
	local SongColor = "#000000";
	local lang = "us";
	if THEME:GetCurLanguage() == "ja" then
		lang = "jp";
	end;

	if GAMESTATE:GetCoinMode() == "CoinMode_Home" then
		SongColor = CSJPSong[songtit] or "#FFFFFF"
	else
		if lang == "jp" then
			SongColor = ACSong[songtit] or "#FFFFFF"
		else
			SongColor = ACAsSong[songtit] or "#FFFFFF"
		end;
	end

	return SongColor;
end;